global_costmap:
  global_frame: map
  static_map: true
  update_frequency: 1.0
  publish_frequency: 1.0
  raytrace_range: 2.0
  resolution: 0.05
  z_resolution: 0.2
  z_voxels: 10
  cost_scaling_factor: 3.0
  inflation_radius: 0.2
