robot_base_frame: base_footprint
robot_radius: 0.35
transform_tolerance: 0.4
update_frequency: 5.0
publish_frequency: 1.0
obstacle_range: 3.0
publish_voxel_map: true

navigation_map:
  map_topic: map

obstacles:
  observation_sources: laser_scan

  laser_scan:
    topic: /robot/laser/scan
    data_type: LaserScan
    sensor_frame: link_laser
    clearing: true
    marking: true
    inf_is_valid: true
    min_obstacle_height: 0.05
    max_obstacle_height: 0.25