local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  static_map: false
  rolling_window: true
  raytrace_range: 3.5
  resolution: 0.05
  z_resolution: 0.15
  z_voxels: 8
  inflation:
    cost_scaling_factor: 10.0
    inflation_radius: 0.40
  width: 2.0
  height: 2.0
  origin_x: 0.0
  origin_y: 0.0
