local_costmap:
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # frame and transform
  global_frame: map
  robot_base_frame: link_footprint

  # rate
  update_frequency: 10.0
  publish_frequency: 10.0

  # map management
  rolling_window: true
  width: 7.0
  height: 7.0
  origin_x: 0.0
  origin_y: 0.0

  inflation_layer:
    cost_scaling_factor: 1.0  # Exponential rate at which the obstacle cost drops off (default: 10). Must be chosen so that the cost value is > 0 at robot's circumscribed radius.
    inflation_radius:    1.5 # Max. distance from an obstacle at which costs are incurred for planning paths. Must be > robot's circumscribed radius.

