local_costmap:
  # frame and transform
  global_frame: odom

  # rate
  update_frequency: 10.0
  publish_frequency: 10.0

  # map management
  rolling_window: true
  width: 4.0
  height: 4.0
  origin_x: 0.0
  origin_y: 0.0