plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

# frame and transform
robot_radius: 0.35
footprint_padding: 0.0
transform_tolerance: 0.1

# rate
update_frequency: 5.0
publish_frequency: 1.0

# map management
resolution: 0.1

# static_layer:
#   enabled: true
#   map_topic: /map

obstacle_layer:
  track_unknown_space: true
  obstacle_range: 4.0
  raytrace_range: 4.0
  observation_sources: scan
  scan:
    topic: /robot/laser/scan
    data_type: LaserScan
    sensor_frame: link_laser
    clearing: true
    marking: true
    inf_is_valid: true
    min_obstacle_height: 0.03
    max_obstacle_height: 0.25

inflation_layer:
  cost_scaling_factor: 20.0  # Exponential rate at which the obstacle cost drops off (default: 10). Must be chosen so that the cost value is > 0 at robot's circumscribed radius.
  inflation_radius:    1.5 # Max. distance from an obstacle at which costs are incurred for planning paths. Must be > robot's circumscribed radius.
