local_costmap:
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # frame and transform
  global_frame: odom
  robot_base_frame: link_footprint

  # rate
  update_frequency: 10.0
  publish_frequency: 10.0

  # map management
  rolling_window: true
  width: 7.0
  height: 7.0
  origin_x: 0.0
  origin_y: 0.0
