
#---standard pioneer footprint---
#---(in meters)---
robot_radius: 0.35
footprint_padding: 0.00

transform_tolerance: 0.2

always_send_full_costmap: true

obstacle_layer:
 enabled: true
 obstacle_range: 4.0
 raytrace_range: 4.5
 track_unknown_space: True
 observation_sources: laser_scan_sensor
 laser_scan_sensor: {data_type: LaserScan, topic: /robot/laser/scan, marking: true, clearing: true, inf_is_valid: true}


inflation_layer:
  enabled:              True
  cost_scaling_factor:  1.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     1.3  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              True
  map_topic:            "/map"
