local_costmap:
  global_frame: map
  robot_base_frame: link_footprint
  update_frequency: 10.0
  publish_frequency: 9.0
  rolling_window: true
  width: 7
  height: 7
  resolution: 0.1
  transform_tolerance: 0.1
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
