robot:
  gazebo_ros_control:
    pid_gains:
      joint_left_wheel: {p: 1.0, i: 1.0, d: 0.0}
      joint_right_wheel: {p: 1.0, i: 1.0, d: 0.0}

  hardware_interface:
    joints:
      - joint_left_wheel
      - joint_right_wheel

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  mobile_base_controller:
    type: diff_drive_controller/DiffDriveController
    publish_rate: 50

    left_wheel: joint_left_wheel
    right_wheel: joint_right_wheel

    base_frame_id: base_footprint

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000.0]

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.25
    velocity_rolling_window_size: 2

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.0  # m/s
        min_velocity           : -0.5 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.8  # m/s^2
        min_acceleration       : -0.4 # m/s^2
        has_jerk_limits        : true
        max_jerk               : 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.7  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 1.5  # rad/s^2
        has_jerk_limits        : true
        max_jerk               : 2.5  # rad/s^3