<?xml version="1.0" ?>

<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="package_name" value="robot_description"/>
  <xacro:property name="robot_name" value="robot"/>

  <xacro:include filename="$(find ${package_name})/urdf/robot.gazebo"/>
  <xacro:include filename="$(find ${package_name})/urdf/materials.xacro"/>
  <xacro:include filename="$(find ${package_name})/urdf/macros.xacro"/>

  <xacro:property name="base_length" value="0.5"/>
  <xacro:property name="base_width" value="0.3"/>
  <xacro:property name="base_height" value="0.07"/>

  <xacro:property name="laser_sensor_size" value="0.05"/>

  <xacro:property name="wheel_diam" value="0.2"/>
  <xacro:property name="wheel_width" value="0.04"/>

  <xacro:property name="collision_inflation" value="1.1"/>

  <xacro:property name="wheel_x_pos" value="${base_length/4}"/>
  <xacro:property name="wheel_y_pos" value="${base_width/2+wheel_width/2}"/>
  <xacro:property name="wheel_z_pos" value="0"/>

  <link name="base_footprint"/>
  <joint name="joint_base_footprint" type="fixed">
    <parent link="base_footprint"/>
    <child link="link_chassis"/>
    <origin xyz="0.0 0.0 ${wheel_diam/2}"/>
  </joint>

  <link name="link_chassis">
    <!-- body -->
    <collision name="collision_chassis">
      <geometry>
        <box size="${base_length*collision_inflation} ${base_width*collision_inflation} ${base_height*collision_inflation}"/>
      </geometry>
    </collision>
    <visual name="chassis_visual">
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <!-- caster -->
    <collision name="caster_rear_collision">
      <origin rpy=" 0 0 0" xyz="${-base_length/4} 0 ${-wheel_diam/4}"/>
      <geometry>
        <sphere radius="${wheel_diam/4}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name="caster_rear_visual">
      <origin rpy=" 0 0 0" xyz="${-base_length/4} 0 ${-wheel_diam/4}"/>
      <geometry>
        <sphere radius="${wheel_diam/4}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <!-- pose and inertial -->
    <pose>0 0 0.1 0 0 0</pose>
    <xacro:base_inertia m="5" x="${base_length}" y="${base_width}" z="${base_height}"
      o_xyz="0 0 0" o_rpy="0 0 0.1"/>    
  </link>

  <xacro:wheel side="right" base_link="link_chassis"
    m="0.2" r="${wheel_diam/2}" l="${wheel_width}"
    x_pos="${wheel_x_pos}" y_pos="${-wheel_y_pos}" z_pos="${wheel_z_pos}" />

  <xacro:wheel side="left" base_link="link_chassis"
    m="0.2" r="${wheel_diam/2}" l="${wheel_width}"
    x_pos="${wheel_x_pos}" y_pos="${wheel_y_pos}" z_pos="${wheel_z_pos}" />
    

  <joint name="joint_laser" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${base_length/2 + laser_sensor_size/2} 0 0" rpy="0 0 0"/>
    <parent link="link_chassis"/>
    <child link="link_laser"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="link_laser">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${laser_sensor_size} ${laser_sensor_size} ${laser_sensor_size}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-laser_sensor_size/10} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${laser_sensor_size*0.8} ${laser_sensor_size} ${laser_sensor_size}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <visual>
      <origin xyz="${laser_sensor_size*0.25} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${laser_sensor_size*0.5} ${laser_sensor_size*0.5} ${laser_sensor_size*0.5}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
</robot>
