base_local_planner: "dwa_local_planner/DWAPlannerROS"

DWAPlannerROS:
# Robot Configuration Parameters
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_th: 2.0
  acc_lim_trans: 0.5

  max_vel_trans:  2.0
  min_vel_trans:  0.0

  max_vel_x: 2.0
  min_vel_x: 0.0

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_theta: 2.0
  min_vel_theta: 0.1
  holohomic_robot: false

# Goal Tolerance Parametes
  yaw_goal_tolerance: 0.10
  xy_goal_tolerance: 0.20
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 4.0
  vx_samples: 10
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 32
  goal_distance_bias: 20
  occdist_scale: 0.05
  forward_point_distance: 0.0
  stop_time_buffer: 0.2
  scaling_speed: 0.25 # seems useless
  max_scaling_factor: 0.2 # seems useless

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.3

# Global Plan Parameters
  prune_plan: true

# Debugging
  # publish_traj_pc : true
  # publish_cost_grid_pc: true
