base_local_planner: "teb_local_planner/TebLocalPlannerROS"

TebLocalPlannerROS:
# Robot Configuration Parameters
  acc_lim_x: 1.0
  acc_lim_theta: 2.5

  max_vel_x: 0.1
  max_vel_x_backwards: 0.1
  max_vel_theta: 1.0
  min_turning_radius: 0

  max_vel_y: 0.0
  acc_lim_y: 0.0

  footprint_model:
    type: circular
    radius: 0.35

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.17
  free_goal_velocity: false

# Trajectory Configuration Parameters
  dt_ref: 0.3
  dt_hysteresis: 0.03
  min_samples: 3
  global_plan_overwrite_orientation: true
  global_plan_viapoint_sep: -1
  max_global_plan_lookahead_dist: 2.0
  force_reinit_new_goal_dist: 1.0
  feasibility_check_no_poses: 4
  shrink_horizon_backup: true
  allow_init_with_backwards_motion: false
  exact_arc_length: false
  shrink_horizon_min_duration: 10.0

# Obstacle Parameters
  min_obstacle_dist: 0.7
  include_costmap_obstacles: false
  costmap_obstacles_behind_robot_dist: 2.0
  inflation_dist: 0.75
  include_dynamic_obstacles: false
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_association_cutoff_factor: 5

# Optimization Parameters
  no_inner_iterations: 5
  no_outer_iterations: 4
  penalty_epsilon: 0.05
  weight_max_vel_x: 2.0
  weight_max_vel_theta: 1.0
  weight_acc_lim_x: 1.0
  weight_acc_lim_theta: 1.0
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1.0
  weight_optimaltime: 1.0
  weight_obstacle: 50.0
  weight_viapoint: 1.0
  weight_inflation: 0.1
  weight_adapt_factor: 2.0

# Parallel Planning in distinctive Topologies
  enable_homotopy_class_planning: true
  enable_multithreading: true
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100
  selection_viapoint_cost_scale: 1.0
  selection_alternative_time_cost: false
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 6
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 1.0
  viapoints_all_candidates: true
  switching_blocking_period: 0.0

# Debugging
  publish_feedback: true
  visualize_hc_graph: true
