base_local_planner: "base_local_planner/TrajectoryPlannerROS"

TrajectoryPlannerROS:
# Robot Configuration Parameters
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 0.5

  max_vel_x: 2.0
  min_vel_x: 0.0

  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.5

  escape_vel: -1.0
  holonomic_robot: false


# Goal Tolerance Parametes
  xy_goal_tolerance: 0.20
  yaw_goal_tolerance: 0.10
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 4.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 20
  vtheta_samples: 60
  controller_frequency: 8.0

# Trajectory Scoring Parameters
  meter_scoring: true
  path_distance_bias: 2.0
  goal_distance_bias: 1.6
  occdist_scale: 0.035
  heading_lookahead: 0.5
  heading_scoring: false
  dwa: false
  global_frame_id: odom

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Global Plan
  prune_plan: true

# Debugging
  # publish_traj_pc : true
  # publish_cost_grid_pc: true
